import { type FightEvent } from '../types';

export const MOCK_EVENTS: FightEvent[] = [
    {
        id: '1',
        title: 'High Nocaute: Edição 45 - A Revanche',
        slug: 'high-nocaute-45',
        event_name: 'High Nocaute 45',
        fight_date: '2025-11-15',
        category: 'Pesos Pesados',
        modality: 'MMA',
        tags: ['Silva', 'Souza', 'Cinturão'],
        teaser_url: 'https://images.unsplash.com/photo-1544367563-12123d8965cd?q=80&w=1200&auto=format&fit=crop',
        thumbnailUrl: 'https://images.unsplash.com/photo-1544367563-12123d8965cd?q=80&w=1200&auto=format&fit=crop',
        price_highlight: 29.90,
        price_full_bundle: 49.90,
        is_active: true,
        // Mantendo compatibilidade visual temporária
        description: 'A maior revanche do ano! Silva vs. Souza lutando pelo cinturão dos pesos pesados.',
    },
    {
        id: '2',
        title: 'Fight Night: Desafio de Titãs',
        slug: 'fight-night-titas',
        event_name: 'Fight Night',
        fight_date: '2025-10-20',
        category: 'Absoluto',
        modality: 'Jiu-Jitsu',
        tags: ['Grappling', 'Submission'],
        teaser_url: 'https://images.unsplash.com/photo-1614959443213-911197779951?q=80&w=1200&auto=format&fit=crop',
        thumbnailUrl: 'https://images.unsplash.com/photo-1614959443213-911197779951?q=80&w=1200&auto=format&fit=crop',
        price_highlight: 34.90,
        price_full_bundle: 54.90,
        is_active: true,
        description: 'Uma noite inesquecível com os melhores lutadores do circuito nacional.',
    },
    {
        id: '3',
        title: 'High Nocaute: Novos Talentos',
        slug: 'high-nocaute-novos',
        event_name: 'High Nocaute',
        fight_date: '2025-09-05',
        category: 'Leve',
        modality: 'Muay Thai',
        tags: ['Striking', 'Revelação'],
        teaser_url: 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?q=80&w=1200&auto=format&fit=crop',
        thumbnailUrl: 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?q=80&w=1200&auto=format&fit=crop',
        price_highlight: 19.90,
        price_full_bundle: 39.90,
        is_active: true,
        description: 'Descubra as próximas estrelas do MMA nacional neste evento eletrizante.',
    },
];
